import localFont from "next/font/local";
import "../globals.css";
import Image from "next/image";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Current Location",
  description: "Generated by Current Location",
};

export default function RootLayout({
  aqi,
  weather,
  wind,
  temperature,
  children,
}) {
  return (
    <>
      <div className="wrapper">
        <Image
          src="/images/background.png"
          className="bg-img"
          width={700}
          height={1200}
          alt="background"
        />
        <div className="overlay"></div>
        <main className="!z-50 h-screen">
          <div className="container">
            <div className="grid grid-cols-1 lg:grid-cols-4 md:grid-cols-2 gap-5 py-16 lg:gap-6 2xl:gap-10 2xl:py-20">
              {aqi}
              {weather}
              {temperature}
              {wind}
              {children}
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
